export const ANALYTICS_CONSTANTS = {
  CORRELATION_THRESHOLDS: {
    STRONG: 0.7,
    MODERATE: 0.4,
    WEAK: 0.2
  },
  MINIMUM_DATA_POINTS: 7,
  PREDICTION_CONFIDENCE_THRESHOLD: 0.6,
  PATTERN_DETECTION_WINDOW: 14
} as const;
