// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqzxauobycefqhcvguck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxenhhdW9ieWNlZnFoY3ZndWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTM4MjQsImV4cCI6MjA2NTAyOTgyNH0.x0NJ4or952au2bgj7kHe65-bIz71Aeb9zywVzbkig7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);